export const FORM_PHASES = [
  { id: 'personal', name: 'Datos Personales', color: 'blue' },
  { id: 'academic', name: 'Datos Académicos', color: 'purple' },
  { id: 'work', name: 'Historia Laboral', color: 'emerald' },
];

export const QUESTIONS = [
  {
    id: 'nombre',
    phaseId: 'personal',
    question: '¿Cuál es tu nombre?',
    description: 'Empecemos por lo básico.',
    type: 'text',
    placeholder: 'Escribe tu nombre aquí...',
    required: false,
  },
  {
    id: 'apellido',
    phaseId: 'personal',
    question: '¿Y tu apellido?',
    type: 'text',
    placeholder: 'Escribe tu apellido aquí...',
    required: false,
  },
  {
    id: 'tipo_documento',
    phaseId: 'personal',
    question: 'Selecciona tu tipo de documento',
    type: 'select',
    required: true,
    options: [
      { label: 'Cédula de ciudadanía', value: 'CC' },
      { label: 'Cédula de extranjería', value: 'CE' },
      { label: 'Pasaporte', value: 'PA' },
    ],
  },
  {
    id: 'numero_documento',
    phaseId: 'personal',
    question: '¿Cuál es tu número de documento?',
    type: 'text',
    placeholder: 'Ingresa el número sin puntos ni comas',
    required: true,
  },
  {
    id: 'movil',
    phaseId: 'personal',
    question: 'Déjanos tu número de móvil',
    description: 'Para mantenerte al tanto de las novedades.',
    type: 'tel',
    placeholder: 'Ej: 300 123 4567',
    required: true,
  },
  {
    id: 'ciudad',
    phaseId: 'personal',
    question: '¿En qué ciudad resides?',
    type: 'text',
    placeholder: 'Ej: Bogotá, Madrid...',
    required: true,
  },
  {
    id: 'nivel_educativo',
    phaseId: 'academic',
    question: 'Nivel Educativo',
    description: 'Selecciona tu grado de formación académica.',
    type: 'select',
    required: true,
    options: [
      { label: 'Técnico', value: 'tecnico' },
      { label: 'Secundaria', value: 'secundaria' },
      { label: 'Técnico Profesional', value: 'tecnico_profesional' },
      { label: 'Tecnólogo', value: 'tecnologo' },
      { label: 'Universitario', value: 'universitario' },
      { label: 'PostGrado', value: 'postgrado' },
      { label: 'Especialización', value: 'especializacion' },
      { label: 'Maestría', value: 'maestria' },
      { label: 'Doctorado', value: 'doctorado' },
      { label: 'Postdoctorado', value: 'postdoctorado' },
    ],
  },
  {
    id: 'profesiones',
    phaseId: 'academic',
    question: 'Profesiones',
    description: '¿Cuál es tu área de conocimiento?',
    type: 'multiselect',
    required: false,
    options: [
      { label: 'Abogado', value: 'abogado' },
      { label: 'Administración de empresas', value: 'administracion_empresas' },
      { label: 'Administración empresas agroindustriales', value: 'administracion_agro' },
      { label: 'Administrador', value: 'administrador' },
      { label: 'Administrador de negocios internacionales', value: 'negocios_internacionales' },
      { label: 'Administrador aeronáutico', value: 'administrador_aeronautico' },
    ],
  },
  {
    id: 'idiomas',
    phaseId: 'academic',
    question: 'Idiomas',
    description: 'Selecciona los idiomas que dominas.',
    type: 'multiselect',
    required: false,
    options: [
      { label: 'Alemán', value: 'aleman' },
      { label: 'Cantones', value: 'cantones' },
      { label: 'Español', value: 'espanol' },
      { label: 'Francés', value: 'frances' },
      { label: 'Inglés', value: 'ingles' },
      { label: 'Italiano', value: 'italiano' },
      { label: 'Mandarín', value: 'mandarin' },
      { label: 'Portugués', value: 'portugues' },
      { label: 'Ruso', value: 'ruso' },
    ],
  },
  {
    id: 'idioma_nativo',
    phaseId: 'academic',
    question: 'Idioma nativo',
    type: 'select',
    required: false,
    options: [
      { label: 'Alemán', value: 'aleman' },
      { label: 'Cantones', value: 'cantones' },
      { label: 'Español', value: 'espanol' },
      { label: 'Francés', value: 'frances' },
      { label: 'Inglés', value: 'ingles' },
      { label: 'Italiano', value: 'italiano' },
      { label: 'Mandarín', value: 'mandarin' },
      { label: 'Portugués', value: 'portugues' },
      { label: 'Ruso', value: 'ruso' },
    ],
  },
  {
    id: 'tecnologias',
    phaseId: 'academic',
    question: 'Tecnologías',
    description: 'Herramientas que manejas profesionalmente.',
    type: 'multiselect',
    required: false,
    options: [
      { label: 'CAM/CAD', value: 'cam_cad' },
      { label: 'MICROSOFT', value: 'microsoft' },
      { label: 'OFFICE', value: 'office' },
      { label: 'ORACLE', value: 'oracle' },
      { label: 'PROJECT', value: 'project' },
      { label: 'SAP', value: 'sap' },
    ],
  },
];
