export const FORM_PHASES = [
  { id: 'personal', name: 'Datos Personales', color: 'blue' },
  { id: 'academic', name: 'Datos Académicos', color: 'purple' },
  { id: 'work', name: 'Historia Laboral', color: 'emerald' },
];

export const QUESTIONS = [
  {
    id: 'nombre',
    phaseId: 'personal',
    question: '¿Cuál es tu nombre?',
    description: 'Empecemos por lo básico.',
    type: 'text',
    placeholder: 'Escribe tu nombre aquí...',
    required: true,
  },
  {
    id: 'apellido',
    phaseId: 'personal',
    question: '¿Y tu apellido?',
    type: 'text',
    placeholder: 'Escribe tu apellido aquí...',
    required: true,
  },
  {
    id: 'tipo_documento',
    phaseId: 'personal',
    question: 'Selecciona tu tipo de documento',
    type: 'select',
    required: true,
    options: [
      { label: 'Cédula de ciudadanía', value: 'CC' },
      { label: 'Cédula de extranjería', value: 'CE' },
      { label: 'Pasaporte', value: 'PA' },
    ],
  },
  {
    id: 'numero_documento',
    phaseId: 'personal',
    question: '¿Cuál es tu número de documento?',
    type: 'text',
    placeholder: 'Ingresa el número sin puntos ni comas',
    required: true,
  },
  {
    id: 'foto',
    phaseId: 'personal',
    question: 'Sube una foto de perfil',
    description: 'Una imagen profesional ayuda a destacar tu perfil.',
    type: 'upload',
    required: false,
  },
  {
    id: 'genero',
    phaseId: 'personal',
    question: '¿Cuál es tu género?',
    type: 'select',
    required: true,
    options: [
      { label: 'Femenino', value: 'femenino' },
      { label: 'Masculino', value: 'masculino' },
      { label: 'No Binario', value: 'no_binario' },
    ],
  },
  {
    id: 'estado_civil',
    phaseId: 'personal',
    question: '¿Cuál es tu estado civil?',
    type: 'select',
    variant: 'dropdown',
    required: false,
    isDynamic: true,
    options: [],
  },
  {
    id: 'direccion',
    phaseId: 'personal',
    question: '¿Cuál es tu dirección de residencia?',
    type: 'text',
    placeholder: 'Ej: Calle 123 # 45 - 67',
    required: true,
  },
  {
    id: 'movil',
    phaseId: 'personal',
    question: 'Déjanos tu número de móvil',
    description: 'Para mantenerte al tanto de las novedades.',
    type: 'tel',
    placeholder: 'Ej: 300 123 4567',
    required: true,
  },
  {
    id: 'telefono_fijo',
    phaseId: 'personal',
    question: '¿Tienes un teléfono fijo?',
    type: 'tel',
    placeholder: 'Ej: 601 123 4567',
    required: false,
  },
  {
    id: 'fecha_nacimiento',
    phaseId: 'personal',
    question: '¿Cuándo es tu fecha de nacimiento?',
    type: 'date',
    required: true,
  },
  {
    id: 'ciudad',
    phaseId: 'personal',
    question: '¿En qué ciudad resides?',
    type: 'select',
    variant: 'compact',
    required: true,
    isDynamic: true,
    options: [],
  },
  {
    id: 'disponibilidad_movilidad',
    phaseId: 'personal',
    question: '¿Tienes disponibilidad para cambiar de ciudad?',
    type: 'select',
    required: true,
    options: [
      { label: 'Sí', value: 'si' },
      { label: 'No', value: 'no' },
      { label: 'Depende de la oportunidad', value: 'depende' },
    ],
  },
  {
    id: 'linkedin',
    phaseId: 'personal',
    question: 'URL de tu perfil de LinkedIn',
    description: 'Opcional, pero muy recomendado.',
    type: 'text',
    placeholder: 'https://linkedin.com/in/tu-perfil',
    required: false,
  },
  {
    id: 'ciudad_programa',
    phaseId: 'personal',
    question: '¿En qué ciudad quieres tomar el programa?',
    type: 'select',
    required: true,
    options: [
      { label: 'Bogotá', value: 'bogota' },
      { label: 'Cali', value: 'cali' },
      { label: 'Medellín', value: 'medellin' },
      { label: 'Región Caribe', value: 'region_caribe' },
    ],
  },
  {
    id: 'nivel_educativo',
    phaseId: 'academic',
    question: 'Nivel Educativo',
    description: 'Selecciona tu grado de formación académica.',
    type: 'select',
    required: true,
    isDynamic: true,
    variant: 'compact',
    options: [], // Se cargará dinámicamente desde el backend
  },
  {
    id: 'profesiones',
    phaseId: 'academic',
    question: 'Profesiones',
    type: 'multiselect',
    required: true,
    isDynamic: true,
    variant: 'compact',
    options: []
  },
  {
    id: 'idioma_nativo',
    phaseId: 'academic',
    question: 'Idioma nativo',
    description: 'Selecciona tu idioma nativo.',
    type: 'select',
    variant: 'compact',
    required: true,
    isDynamic: true,
    options: [], // Se cargará dinámicamente desde el backend 
  },
  {
    id: 'idiomas',
    phaseId: 'academic',
    question: 'Idiomas',
    description: 'Selecciona los idiomas que dominas y su nivel.',
    type: 'multiselect',
    variant: 'compact',
    required: false,
    isDynamic: true,
    requiresLevel: true,
    options: [], // Se cargará dinámicamente desde el backend
  },
  {
    id: 'tecnologias',
    phaseId: 'academic',
    question: 'Tecnologías',
    description: 'Selecciona las tecnologías que manejas.',
    type: 'multiselect',
    variant: 'compact',
    required: false,
    isDynamic: true,
    options: [], // Se cargará dinámicamente desde el backend 
  },
  {
    id: 'historia_laboral',
    phaseId: 'work',
    question: 'Historia Laboral',
    description: 'Agrega tus experiencias laborales más relevantes.',
    type: 'work_experience',
    required: true,
  }
];

